### ISSUE TITLE
[BUG] Install failure if log files do not exist already

### ISSUE THREAD

**Issue by PhillipOConnor** [Uninett/nav-debian#10] opened 2021-01-05 07:12 UTC
**The bug**
Installation of nav (5.1.1-2) on a fresh Debian 10 that has not had nav before and hence has no log files yet fails with:
`chown: cannot access '/var/log/nav/*.log': No such file or directory`
`chown: cannot access '/var/log/nav/*.log.*gz': No such file or directory`
`dpkg: error processing package nav (--configure):`
`installed nav package post-installation script subprocess returned error exit status 1`

The package status in aptitude is "c" indicating a broken installation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Installation system has not had nav installed before
2. Run aptitude
3. Find nav in the package list
4. Select nav to install (keystrokes: +gg)
5. See errors in install log
6. Package status in aptitude "c"

**Expected behaviour**
Installation without errors and a package status of "i"

**Environment**
 - OS on the NAV server: Debian 10
 - NAV version 5.1.1-2
 - Method of installation: Debian package

**Additional context**
postgreSQL already installed

**Hint**
Creating dummy logs allows the install to work:
`touch /var/log/nav/dummy.log`
`touch /var/log/nav/dummy.log.gz`

**Comment by lunkwill42** [comment] 2021-01-05 13:10
Confirmed. Our CI server has the same problem, however, for some reason, it seems it ran no debian-install jobs between December 7 and January 4. 5.1.1-2 was released before Christmas, so the error must have been present since then.

**Comment by lunkwill42** [comment] 2021-01-05 14:04
Closed in f22a3e1

**Closed** 2021-01-05 14:04 UTC
Labels: bug
